from typing import List, Dict

SHOPPERS: List[Dict] = [
    {
        "id": 1,
        "nom": "InAndStyle Paris",
        "genre_clients": ["femme"],
        "specialites": ["working_girl", "relooking pro", "accompagnement magasin"],
        "styles": ["chic", "élégant", "minimal"],
        "zone": "Paris",
        "formats": ["magasin", "visio"],
        "niveau_budget": ["moyen", "élevé"],
        "tags": ["#working_girl", "#costumes", "#capsule_wardrobe"],
        "note_moyenne": 4.8,
    },
    {
        "id": 2,
        "nom": "Chrysalide Elegance",
        "genre_clients": ["femme", "autre"],
        "specialites": ["colorimétrie", "accompagnement magasin", "mariage"],
        "styles": ["romantique", "chic"],
        "zone": "Paris",
        "formats": ["magasin", "visio"],
        "niveau_budget": ["moyen", "élevé"],
        "tags": ["#mariage", "#robe_soirée", "#colorimétrie"],
        "note_moyenne": 4.7,
    },
    {
        "id": 3,
        "nom": "MoutiStyL La Défense",
        "genre_clients": ["femme"],
        "specialites": ["mode business", "grande taille", "relooking pro"],
        "styles": ["chic", "structuré"],
        "zone": "Paris la défense",
        "formats": ["magasin", "visio"],
        "niveau_budget": ["moyen", "élevé"],
        "tags": ["#grande_taille", "#business", "#executive_style"],
        "note_moyenne": 4.9,
    },
    {
        "id": 4,
        "nom": "StreetWave Lyon",
        "genre_clients": ["homme", "autre"],
        "specialites": ["streetwear", "casual", "budget serré"],
        "styles": ["street", "casual"],
        "zone": "Lyon",
        "formats": ["magasin", "domicile"],
        "niveau_budget": ["bas", "moyen"],
        "tags": ["#street", "#sneakers", "#casual_friday"],
        "note_moyenne": 4.5,
    },
    {
        "id": 5,
        "nom": "Theo",
        "genre_clients": ["femme", "autre"],
        "specialites": ["seconde main", "éco-responsable", "tri dressing"],
        "styles": ["casual", "bohème"],
        "zone": "Marseille",
        "formats": ["magasin", "visio", "domicile"],
        "niveau_budget": ["bas", "moyen"],
        "tags": ["#eco_responsable", "#seconde_main", "#slow_fashion"],
        "note_moyenne": 4.4,
    },
    {
        "id": 6,
        "nom": "ModernGent Bordeaux",
        "genre_clients": ["homme"],
        "specialites": ["costumes", "business casual", "relooking pro"],
        "styles": ["chic", "minimal"],
        "zone": "Bordeaux",
        "formats": ["magasin", "visio"],
        "niveau_budget": ["moyen", "élevé"],
        "tags": ["#costumes", "#business_casual", "#working_man"],
        "note_moyenne": 4.6,
    },
    {
        "id": 7,
        "nom": "Alexandre",
        "genre_clients": ["femme", "homme", "autre"],
        "specialites": ["mode inclusive", "grandes tailles", "non-binaire"],
        "styles": ["casual", "street"],
        "zone": "Lille",
        "formats": ["magasin", "visio"],
        "niveau_budget": ["bas", "moyen"],
        "tags": ["#inclusive", "#diversité", "#grande_taille"],
        "note_moyenne": 4.3,
    },
    {
        "id": 8,
        "nom": "Anatholie",
        "genre_clients": ["femme"],
        "specialites": ["capsule wardrobe", "minimalisme", "tri dressing"],
        "styles": ["minimal", "chic"],
        "zone": "Lyon",
        "formats": ["visio", "domicile"],
        "niveau_budget": ["moyen", "élevé"],
        "tags": ["#capsule_wardrobe", "#minimal", "#tri_dressing"],
        "note_moyenne": 4.7,
    },
    {
        "id": 9,
        "nom": "Maeva",
        "genre_clients": ["femme", "autre"],
        "specialites": ["reprise de confiance", "post-partum", "relooking complet"],
        "styles": ["chic", "casual"],
        "zone": "Toulouse",
        "formats": ["magasin", "domicile", "visio"],
        "niveau_budget": ["bas", "moyen"],
        "tags": ["#confiance_en_soi", "#postpartum", "#glowup"],
        "note_moyenne": 4.8,
    },
    {
        "id": 10,
        "nom": "Event&Style Nice",
        "genre_clients": ["femme", "homme"],
        "specialites": ["événementiel", "mariage", "soirées privées"],
        "styles": ["élégant", "festif"],
        "zone": "Nice",
        "formats": ["magasin", "visio"],
        "niveau_budget": ["moyen", "élevé"],
        "tags": ["#mariage", "#evenementiel", "#soirée"],
        "note_moyenne": 4.6,
    },
    {
        "id": 11,
        "nom": "HaroldStyle Paris",
        "genre_clients": ["femme", "autre"],
        "specialites": ["vintage", "friperies", "éco-responsable"],
        "styles": ["vintage", "bohème", "casual"],
        "zone": "Paris",
        "formats": ["magasin", "visio"],
        "niveau_budget": ["bas", "moyen"],
        "tags": ["#vintage", "#fripes", "#retro", "#slow_fashion"],
        "note_moyenne": 4.5,
    },
    {
        "id": 12,
        "nom": "Manon",
        "genre_clients": ["femme", "homme", "autre"],
        "specialites": ["sportswear", "athleisure", "dressing actif"],
        "styles": ["sport", "casual"],
        "zone": "Lyon",
        "formats": ["magasin", "domicile", "visio"],
        "niveau_budget": ["bas", "moyen"],
        "tags": ["#sportswear", "#athleisure", "#confort"],
        "note_moyenne": 4.4,
    },
    {
        "id": 13,
        "nom": "Anais",
        "genre_clients": ["femme", "autre"],
        "specialites": ["modest fashion", "voilée", "éco-responsable"],
        "styles": ["chic", "minimal"],
        "zone": "Marseille",
        "formats": ["magasin", "visio"],
        "niveau_budget": ["bas", "moyen", "élevé"],
        "tags": ["#modest_fashion", "#voile", "#longueur", "#couvrant"],
        "note_moyenne": 4.7,
    },
    {
        "id": 14,
        "nom": "Nathan",
        "genre_clients": ["femme", "homme"],
        "specialites": ["50+", "senior", "confort chic"],
        "styles": ["chic", "casual"],
        "zone": "Paris",
        "formats": ["magasin", "domicile", "visio/presentiel"],
        "niveau_budget": ["moyen"],
        "tags": ["#senior", "#confort", "#morphologie_changeante"],
        "note_moyenne": 4.6,
    },
    {
        "id": 15,
        "nom": "Stephane",
        "genre_clients": ["autre", "femme", "homme"],
        "specialites": ["ados", "jeunes adultes", "petits budgets"],
        "styles": ["street", "casual", "y2k"],
        "zone": "Dubai",
        "formats": ["magasin", "visio"],
        "niveau_budget": ["bas"],
        "tags": ["#ado", "#lycéen", "#y2k", "#tiktok_style"],
        "note_moyenne": 4.2,
    },
    {
        "id": 16,
        "nom": "AminaStyle",
        "genre_clients": ["homme"],
        "specialites": ["grande taille homme", "relooking pro", "casual chic"],
        "styles": ["casual", "chic"],
        "zone": "Dubai",
        "formats": ["magasin", "presentiel"],
        "niveau_budget": ["bas", "moyen"],
        "tags": ["#plus_size_man", "#grande_taille_homme", "#business_casual"],
        "note_moyenne": 4.5,
    },
    {
        "id": 17,
        "nom": "Camille",
        "genre_clients": ["femme", "homme"],
        "specialites": ["dirigeants", "C-level", "image premium"],
        "styles": ["chic", "élégant", "structuré"],
        "zone": "New York",
        "formats": ["magasin", "domicile", "visio/presentiel"],
        "niveau_budget": ["élevé"],
        "tags": ["#executive", "#luxe", "#costumes_premium"],
        "note_moyenne": 4.9,
    },
    {
        "id": 18,
        "nom": "Theo Créatif",
        "genre_clients": ["femme", "homme", "autre"],
        "specialites": ["créatifs", "artistes", "looks scéniques"],
        "styles": ["avant-garde", "street", "bohème"],
        "zone": "Montpellier",
        "formats": ["magasin", "visio/presentiel"],
        "niveau_budget": ["moyen"],
        "tags": ["#artiste", "#scénique", "#festival", "#coloré"],
        "note_moyenne": 4.4,
    },
    {
        "id": 19,
        "nom": "AndroStyle Paris",
        "genre_clients": ["femme", "homme", "autre"],
        "specialites": ["androgynes", "non-binaire", "genderless"],
        "styles": ["minimal", "street", "chic"],
        "zone": "Paris",
        "formats": ["magasin", "visio"],
        "niveau_budget": ["moyen"],
        "tags": ["#androgynous", "#genderless", "#fluid", "#inclusive"],
        "note_moyenne": 4.6,
    },
    {
        "id": 20,
        "nom": "Angel Glow",
        "genre_clients": ["femme"],
        "specialites": ["grossesse", "post-partum", "morphologie évolutive"],
        "styles": ["casual", "confort", "chic"],
        "zone": "Lyon",
        "formats": ["magasin", "domicile", "presentiel"],
        "niveau_budget": ["bas", "moyen"],
        "tags": ["#maternité", "#grossesse", "#postpartum", "#confort"],
        "note_moyenne": 4.7,
    },

    # --- NOUVEAUX PROFILS POUR PLUS DE SCÉNARIOS ---

    {
        "id": 21,
        "nom": "Nora UrbanStyle",
        "genre_clients": ["femme", "autre"],
        "specialites": ["streetwear", "bureau créatif", "petits budgets"],
        "styles": ["street", "casual", "tendance"],
        "zone": "Nantes",
        "formats": ["magasin", "visio"],
        "niveau_budget": ["bas", "moyen"],
        "tags": ["#street_nantes", "#creative_office", "#petit_budget"],
        "note_moyenne": 4.3,
    },
    {
        "id": 22,
        "nom": "Léa Scandinave",
        "genre_clients": ["femme"],
        "specialites": ["minimalisme", "capsule wardrobe", "éco-responsable"],
        "styles": ["minimal", "chic"],
        "zone": "Rennes",
        "formats": ["visio", "domicile"],
        "niveau_budget": ["moyen", "élevé"],
        "tags": ["#scandi", "#capsule", "#neutres"],
        "note_moyenne": 4.8,
    },
    {
        "id": 23,
        "nom": "Karim Tailored",
        "genre_clients": ["homme"],
        "specialites": ["costumes", "tenues cérémonie", "business elite"],
        "styles": ["chic", "structuré"],
        "zone": "Strasbourg",
        "formats": ["magasin", "visio"],
        "niveau_budget": ["moyen", "élevé"],
        "tags": ["#tailleur", "#costume_3pièces", "#mariage_homme"],
        "note_moyenne": 4.7,
    },
    {
        "id": 24,
        "nom": "Sofia Riviera",
        "genre_clients": ["femme"],
        "specialites": ["summer resort", "soirées riviera", "vacances chic"],
        "styles": ["festif", "bohème", "élégant"],
        "zone": "Cannes",
        "formats": ["magasin", "visio"],
        "niveau_budget": ["moyen", "élevé"],
        "tags": ["#riviera", "#vacances", "#soirée_plage"],
        "note_moyenne": 4.6,
    },
    {
        "id": 25,
        "nom": "Élise GreenWardrobe",
        "genre_clients": ["femme", "autre"],
        "specialites": ["seconde main", "friperies", "zéro déchet"],
        "styles": ["casual", "bohème"],
        "zone": "Grenoble",
        "formats": ["magasin", "domicile", "visio"],
        "niveau_budget": ["bas", "moyen"],
        "tags": ["#green", "#fripes_premium", "#eco"],
        "note_moyenne": 4.4,
    },
    {
        "id": 26,
        "nom": "Yanis CasualPlus",
        "genre_clients": ["homme"],
        "specialites": ["grande taille", "casual chic", "weekly outfits"],
        "styles": ["casual", "chic"],
        "zone": "Montpellier",
        "formats": ["magasin", "visio"],
        "niveau_budget": ["bas", "moyen"],
        "tags": ["#plus_size", "#casual_plus", "#confort_homme"],
        "note_moyenne": 4.5,
    },
    {
        "id": 27,
        "nom": "Lucie CampusLook",
        "genre_clients": ["femme", "autre"],
        "specialites": ["étudiants", "oraux d’école", "stages"],
        "styles": ["casual", "tendance", "chic"],
        "zone": "Poitiers",
        "formats": ["visio", "magasin"],
        "niveau_budget": ["bas", "moyen"],
        "tags": ["#campus", "#oraUX", "#starter_pack"],
        "note_moyenne": 4.2,
    },
    {
        "id": 28,
        "nom": "Mira GlobalChic",
        "genre_clients": ["femme", "homme", "autre"],
        "specialites": ["expats", "voyages pro", "image internationale"],
        "styles": ["chic", "minimal", "élégant"],
        "zone": "Bruxelles",
        "formats": ["visio", "magasin"],
        "niveau_budget": ["moyen", "élevé"],
        "tags": ["#expat", "#business_travel", "#global"],
        "note_moyenne": 4.9,
    },
]
